Repository kubeflow/metadata, pull requests merged in 2019-11, with the labels that each got.

#157 Add retry when connecting metadata store
  server/main.go
Labels: approved, lgtm, size/S

#158 Pin ml-metadata dependency to v0.14.0
  WORKSPACE
Labels: approved, lgtm, size/XS

#156 Update Python SDK to use MLMD gRPC service
  .gitignore
  sdk/python/kubeflow/metadata/metadata.py
  sdk/python/setup.py
  sdk/python/tests/test.py
  test/scripts/setup-services-run-tests.sh
Labels: approved, lgtm, size/XL

#159 [MLMD Lineage] Initial Lineage explorer draft implemented
  .gitignore
  frontend/gen_grpc_web_protos.sh
  frontend/gen_licenses.js
  frontend/package-lock.json
  frontend/package.json
  frontend/server/server.ts
  frontend/src/Css.tsx
  frontend/src/__mocks__/typestyle.ts
  frontend/src/apis/metadata/metadata_store.proto
  frontend/src/apis/metadata/metadata_store_service.proto
  frontend/src/components/EdgeCanvas.css
  frontend/src/components/EdgeCanvas.tsx
  frontend/src/components/LineChart.d.ts
  frontend/src/components/LineageCard.css
  frontend/src/components/LineageCard.tsx
  frontend/src/components/LineageCardColumn.css
  frontend/src/components/LineageCardColumn.tsx
  frontend/src/components/LineageCardRow.css
  frontend/src/components/LineageCardRow.tsx
  frontend/src/components/LineageTypes.ts
  frontend/src/fonts.scss
  frontend/src/generated/src/apis/metadata/metadata_store_pb.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_pb.js
  frontend/src/generated/src/apis/metadata/metadata_store_pb_service.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_pb_service.js
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb.js
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb_service.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb_service.js
  frontend/src/lib/Api.ts
  frontend/src/pages/ArtifactList.test.tsx
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/LineageView.tsx
  frontend/src/pages/Page.tsx
  frontend/src/pages/__snapshots__/ArtifactList.test.tsx.snap
  frontend/start-proxy.sh
  frontend/tsconfig.json
  frontend/tslint.json
  package-lock.json
Labels: approved, area/front-end, area/metadata, lgtm, priority/p0, size/XXL

#164 Add arm64 support for metadata
  Dockerfile
  Makefile
  dockerfiles/Dockerfile-linux-base.aarch64
Labels: approved, lgtm, needs-ok-to-test, size/S

#165 Replace MLMD HTTP API requests with gRPC-Web requests to ml_metadata
  frontend/gen_grpc_web_protos.js
  frontend/gen_grpc_web_protos.sh
  frontend/package-lock.json
  frontend/package.json
  frontend/src/TestUtils.ts
  frontend/src/__mocks__/grpc-web.ts
  frontend/src/components/ModelInfo.test.tsx
  frontend/src/components/ModelInfo.tsx
  frontend/src/components/ResourceInfo.test.tsx
  frontend/src/components/ResourceInfo.tsx
  frontend/src/components/__snapshots__/ResourceInfo.test.tsx.snap
  frontend/src/generated/src/apis/metadata/metadata_store_pb.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_pb_service.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_pb_service.js
  frontend/src/generated/src/apis/metadata/metadata_store_service_grpc_web_pb.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_service_grpc_web_pb.js
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb_service.d.ts
  frontend/src/generated/src/apis/metadata/metadata_store_service_pb_service.js
  frontend/src/lib/Api.ts
  frontend/src/lib/Utils.test.ts
  frontend/src/lib/Utils.tsx
  frontend/src/pages/ArtifactDetails.test.tsx
  frontend/src/pages/ArtifactDetails.tsx
  frontend/src/pages/ArtifactList.test.tsx
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/ExecutionDetails.tsx
  frontend/src/pages/ExecutionList.tsx
  frontend/src/pages/Page.tsx
  frontend/src/pages/__snapshots__/ArtifactDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/ArtifactList.test.tsx.snap
  frontend/start-proxy.js
  frontend/start-proxy.sh
Labels: approved, lgtm, size/XXL

#167 Python SDK improvements
  sdk/python/kubeflow/metadata/metadata.py
  sdk/python/setup.py
  sdk/python/tests/run_tests.sh
  sdk/python/tests/test.py
Labels: approved, lgtm, size/L

#172 Tweak Artifact Details page
  frontend/src/pages/ArtifactDetails.test.tsx
  frontend/src/pages/ArtifactDetails.tsx
  frontend/src/pages/LineageView.tsx
  frontend/src/pages/__snapshots__/ArtifactDetails.test.tsx.snap
Labels: approved, area/front-end, area/metadata, lgtm, size/XXL

#169 Update MLMD version to 0.15.1 with bug fixes
  WORKSPACE
Labels: approved, lgtm, size/XS

#168 Add sphinx docs for Python SDK.
  .readthedocs.yaml
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  docs/source/md.rst
  sdk/python/kubeflow/metadata/metadata.py
Labels: approved, lgtm, size/L

#170 Add LineageViewActionBar
  frontend/src/components/LineageActionBar.test.tsx
  frontend/src/components/LineageActionBar.tsx
  frontend/src/components/LineageCard.tsx
  frontend/src/components/LineageCardColumn.tsx
  frontend/src/components/LineageCardRow.tsx
  frontend/src/components/__snapshots__/LineageActionBar.test.tsx.snap
  frontend/src/pages/ArtifactDetails.tsx
  frontend/src/pages/LineageView.tsx
  frontend/src/pages/__snapshots__/ArtifactDetails.test.tsx.snap
Labels: approved, lgtm, size/XXL

#173 Tweak lifecycle in EdgeCanvas to avoid setState() in render()
  frontend/src/components/EdgeCanvas.css
  frontend/src/components/EdgeCanvas.tsx
  frontend/src/pages/__snapshots__/ArtifactDetails.test.tsx.snap
Labels: approved, area/front-end, area/metadata, lgtm, size/L

#175 Fixed linter issues, and updated scripts to work on windows
  frontend/gen_grpc_web_protos.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/LineageView.tsx
Labels: approved, area/front-end, area/metadata, lgtm, priority/p1, size/L
