Repository kubeflow/metadata, pull requests merged in 2019-07, with the labels that each got.

#80 Add homepage entry to allow serving from non-root folder
  frontend/package.json
Labels: approved, lgtm, size/XS

#69 Add lineage tracking into Python SDK
  sdk/python/demo.ipynb
  sdk/python/kfmd/metadata.py
  sdk/python/tests/test.py
Labels: approved, lgtm, size/XL

#83 Update python SDK version
  sdk/python/setup.py
Labels: approved, lgtm, size/XS

#84 Add artifact & execution map to ListEvents endpoint
  api/service.pb.go
  api/service.proto
  api/service.swagger.json
  service/service.go
  service/service_test.go
Labels: approved, lgtm, size/L

#85 Typo fix in model.md
  schema/alpha/docs/artifacts/model.md
Labels: approved, lgtm, size/XS

#90 Fix e2e test
  test/scripts/create-cluster.sh
  test/workflows/app.yaml
Labels: approved, lgtm, size/XS

#95 Adds grouping/expansion to Artifacts List view - Copied from #82
  frontend/Dockerfile
  frontend/package.json
  frontend/src/components/CustomTable.test.tsx
  frontend/src/components/CustomTable.tsx
  frontend/src/components/__snapshots__/CustomTable.test.tsx.snap
  frontend/src/pages/ArtifactList.test.tsx
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/__snapshots__/ArtifactList.test.tsx.snap
Labels: approved, lgtm, size/XXL

#86 Fix ArtifactType/ExecutionType listing
  WORKSPACE
  mocks/BUILD.bazel
  mocks/metadata_store_service_client_mock.go
  service/metadata_store.go
  service/service.go
Labels: approved, lgtm, size/XL

#92 update some logs
  schemaparser/register.go
Labels: approved, lgtm, ok-to-test, size/XS

#98 Update docs
  README.md
  schema/alpha/artifacts/model.json
  sdk/python/README.md
  sdk/python/demo.ipynb
  test/e2e/artifact_model_1.json
Labels: approved, lgtm, size/M

#100 change a variable name
  service/service_test.go
Labels: approved, lgtm, ok-to-test, size/S

#99 Update Python library
  Makefile
  sdk/python/demo.ipynb
  sdk/python/kfmd/metadata.py
  sdk/python/setup.py
  sdk/python/tests/test.py
  test/scripts/setup-services-run-tests.sh
Labels: approved, lgtm, size/L

#104 Split the dockerfile
  Dockerfile
  dockerfiles/Dockerfile-linux-base
Labels: approved, lgtm, size/M
