Repository kubeflow/metadata, pull requests merged in 2019-04, with the labels that each got.

#2 Roadmap for v0.6
  roadmap.md
Labels: approved, lgtm, size/S

#3 Add basic gRPC-based server with HTTP endpoints (using grpc-gateway)
  .gitignore
  BUILD.bazel
  README.md
  WORKSPACE
  api/BUILD.bazel
  api/README.md
  api/api.pb.go
  api/api.pb.gw.go
  api/api.proto
  api/generate_proto.sh
  go.mod
  go.sum
  server/BUILD.bazel
  server/main.go
  service/BUILD.bazel
  service/service.go
  service/service_test.go
Labels: approved, lgtm, size/XL

#10 Use JSON schema to define metadata.
  go.mod
  go.sum
  schema/README.md
  schema/alpha/artifacts/artifact.json
  schema/alpha/artifacts/data_set.json
  schema/alpha/artifacts/executable.json
  schema/alpha/artifacts/metrics.json
  schema/alpha/artifacts/model.json
  schema/alpha/containers/workspace.json
  schema/alpha/docs/artifacts/artifact.md
  schema/alpha/docs/artifacts/data_set.md
  schema/alpha/docs/artifacts/executable.md
  schema/alpha/docs/artifacts/metrics.md
  schema/alpha/docs/artifacts/model.md
  schema/alpha/docs/containers/workspace.md
  schema/alpha/docs/entity.md
  schema/alpha/docs/execution.md
  schema/alpha/entity.json
  schema/alpha/execution.json
  schema/examples/alpha/artifact.json
  schema/examples/alpha/data_set.json
  schema/examples/alpha/entity.json
  schema/examples/alpha/executable.json
  schema/examples/alpha/execution.json
  schema/generate_doc.sh
  schema/schema_test.go
Labels: approved, lgtm, size/XXL

#14 Add Prow job for tests
  prow_config.yaml
  test/scripts/unittests.sh
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/base.libsonnet
  test/workflows/environments/test/main.jsonnet
  test/workflows/environments/test/params.libsonnet
Labels: approved, lgtm, size/L

#16 Add Dockerfile for building service image
  Dockerfile
Labels: approved, lgtm, size/S
