Repository kubeflow/metadata, pull requests merged in 2019-05, with the labels that each got.

#21 Check return value of http.ListenAndServe
  server/main.go
Labels: approved, lgtm, size/XS

#23 Add common gitignore patterns
  .gitignore
Labels: approved, lgtm, size/M

#25 Add ML MetaData as dependency
  Makefile
  WORKSPACE
  go.mod
  go.sum
  ml_metadata/BUILD.bazel
  ml_metadata/Dockerfile
  ml_metadata/metadata_source.pb.go
  ml_metadata/metadata_store.pb.go
  ml_metadata/metadata_store_service.pb.go
  ml_metadata/proto/BUILD.bazel
  ml_metadata/proto/metadata_source.proto
  ml_metadata/proto/metadata_store.proto
  ml_metadata/proto/metadata_store_service.proto
  schema/BUILD.bazel
  server/BUILD.bazel
  server/main.go
  service/BUILD.bazel
  service/service.go
Labels: approved, lgtm, size/XXL

#24 Add initial API and data model definitions.
  BUILD.bazel
  api/BUILD.bazel
  api/api.pb.go
  api/api.proto
  api/service.pb.go
  api/service.pb.gw.go
  api/service.proto
Labels: approved, lgtm, size/XXL

#26 Init type spec for model, metrics and workspace
  go.sum
  schema/README.md
  schema/alpha/artifacts/artifact.json
  schema/alpha/artifacts/executable.json
  schema/alpha/artifacts/metrics.json
  schema/alpha/artifacts/model.json
  schema/alpha/containers/workspace.json
  schema/alpha/docs/artifacts/artifact.md
  schema/alpha/docs/artifacts/executable.md
  schema/alpha/docs/artifacts/metrics.md
  schema/alpha/docs/artifacts/model.md
  schema/alpha/docs/containers/workspace.md
  schema/alpha/docs/execution.md
  schema/alpha/execution.json
  schema/examples/alpha/artifact.json
  schema/examples/alpha/data_set.json
  schema/examples/alpha/entity.json
  schema/examples/alpha/executable.json
  schema/examples/alpha/execution.json
  schema/schema_test.go
Labels: approved, lgtm, size/XXL

#15 Add JSON schema parser to the server & convert schemas to MLMD types
  Makefile
  README.md
  WORKSPACE
  go.mod
  go.sum
  mocks/BUILD.bazel
  mocks/metadata_store_service_client_mock.go
  schema/BUILD.bazel
  schemaparser/BUILD.bazel
  schemaparser/schemajson.go
  schemaparser/schemajson_test.go
  schemaparser/schemaset.go
  schemaparser/schemaset_test.go
  schemaparser/testdata/base.json
  schemaparser/testdata/ext.json
  server/main.go
  service/BUILD.bazel
  service/service.go
  service/service_test.go
Labels: approved, lgtm, size/XXL

#32 Add third_party/ml_metadata README file.
  third_party/ml_metadata/README.md
Labels: approved, lgtm, size/S

#31 Make schema registration to call metadata service directly instead of MLMD
  Makefile
  README.md
  go.mod
  go.sum
  schemaparser/BUILD.bazel
  schemaparser/register.go
  schemaparser/register_test.go
  schemaparser/schemaset.go
  schemaparser/schemaset_test.go
  server/BUILD.bazel
  server/main.go
  service/BUILD.bazel
  service/schema_service.go
  service/schema_service_test.go
  third_party/ml_metadata/go.mod
  third_party/ml_metadata/go.sum
Labels: approved, lgtm, size/L

#34 Fix CGO flags for running on Linux
  third_party/ml_metadata/metadata_store/metadata_store_go_wrap/metadata_store_go_wrap.go
Labels: approved, lgtm, size/S

#33 Generate Python client to call REST endpoints using swagger.
  .gitignore
  Makefile
  api/BUILD.bazel
  api/api.swagger.json
  api/generate_proto.sh
  api/service.swagger.json
Labels: approved, lgtm, size/L

#29 Add initial metadata python API
  .gitignore
  python_client/README.md
  python_client/__init__.py
  python_client/concepts.png
  python_client/metadata.py
  python_client/tests/__init__.py
  python_client/tests/run_tests.sh
  python_client/tests/test.py
Labels: approved, lgtm, size/L

#37 Remove MLMD grpc server code
  Makefile
  ml_metadata/BUILD.bazel
  ml_metadata/Dockerfile
  ml_metadata/metadata_source.pb.go
  ml_metadata/metadata_store.pb.go
  ml_metadata/metadata_store_service.pb.go
  ml_metadata/proto/BUILD.bazel
  ml_metadata/proto/metadata_source.proto
  ml_metadata/proto/metadata_store.proto
  ml_metadata/proto/metadata_store_service.proto
  test/scripts/unittests.sh
Labels: approved, lgtm, size/XXL

#39 add myself to the reviews of the python packages
  python_client/OWNERS
Labels: approved, lgtm, size/XS

#36 Use bazel to build docker image
  Dockerfile
Labels: approved, lgtm, size/S

#38 Update the swagger generation code
  Makefile
Labels: approved, lgtm, size/S

#41 release python sdk
  .gitignore
  Makefile
  sdk/OWNERS
  sdk/python/README.md
  sdk/python/build.sh
  sdk/python/concepts.png
  sdk/python/kfmd/__init__.py
  sdk/python/kfmd/metadata.py
  sdk/python/setup.py
  sdk/python/tests/__init__.py
  sdk/python/tests/run_tests.sh
  sdk/python/tests/test.py
Labels: approved, lgtm, size/M

#35 Add Artifact handlers.
  BUILD.bazel
  api/BUILD.bazel
  api/api.pb.go
  api/api.proto
  api/service.pb.go
  api/service.pb.gw.go
  api/service.proto
  api/service.swagger.json
  schemaparser/register.go
  service/BUILD.bazel
  service/metadata_store.go
  service/service.go
  service/service_test.go
Labels: approved, lgtm, size/XXL
