Repository kubeflow/metadata, pull requests merged in 2019-10, with the labels that each got.

#126 Add resource watcher to log metadata
  go.mod
  go.sum
  test/scripts/setup-services-run-tests.sh
  watcher/Makefile
  watcher/README.md
  watcher/architecture.png
  watcher/dockerfiles/Dockerfile
  watcher/dockerfiles/resource_list.json
  watcher/dockerfiles/role.yaml
  watcher/dockerfiles/rolebinding.yaml
  watcher/dockerfiles/watcher.yaml
  watcher/handlers/metalogger.go
  watcher/main/main.go
  watcher/watcher.go
Labels: approved, lgtm, size/XL

#144 Add Bobgy to frontend approver and reviewer
  frontend/OWNERS
Labels: approved, lgtm, size/XS

#139 Add Artifact Details tab bar
  frontend/src/atoms/MD2Tabs.test.tsx
  frontend/src/atoms/MD2Tabs.tsx
  frontend/src/atoms/__snapshots__/MD2Tabs.test.tsx.snap
  frontend/src/pages/ArtifactDetails.test.tsx
  frontend/src/pages/ArtifactDetails.tsx
  frontend/src/pages/__snapshots__/ArtifactDetails.test.tsx.snap
Labels: approved, area/front-end, area/metadata, kind/feature, lgtm, ok-to-test, size/XXL

#142 Update watcher readme
  watcher/README.md
  watcher/dockerfiles/watcher.yaml
  watcher/watcher_example.png
Labels: approved, lgtm, size/S

#143 Owner Updates to add Kwasi / AP and remove Riley
  frontend/OWNERS
Labels: approved, area/front-end, area/metadata, priority/p0, size/XS
