Repository kubeflow/metadata, pull requests merged in 2019-08, with the labels that each got.

#96 update Dockerfile to support power
  Dockerfile
  dockerfiles/Dockerfile-linux-base.ppc64le
Labels: approved, lgtm, needs-ok-to-test, size/S

#109 in example notebook, uncomment installs; a few typo fixes
  sdk/python/README.md
  sdk/python/demo.ipynb
  sdk/python/kfmd/metadata.py
Labels: approved, lgtm, size/S

#112 Regenerates swagger APIs
  frontend/src/apis/service/api.ts
Labels: approved, lgtm, size/L

#111 Displays all properties and custom properties in details page
  frontend/server/server.ts
  frontend/src/Css.tsx
  frontend/src/components/ArtifactInfo.tsx
  frontend/src/components/CustomTable.tsx
  frontend/src/components/__snapshots__/ArtifactInfo.test.tsx.snap
  frontend/src/lib/Utils.ts
  frontend/src/pages/ArtifactDetails.tsx
  frontend/src/pages/ArtifactList.test.tsx
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/__snapshots__/ArtifactDetails.test.tsx.snap
  frontend/src/pages/__snapshots__/ArtifactList.test.tsx.snap
Labels: approved, lgtm, size/XXL

#113 Reorganize artifact list page
  frontend/src/lib/Api.ts
  frontend/src/pages/ArtifactList.test.tsx
  frontend/src/pages/ArtifactList.tsx
  frontend/src/pages/__snapshots__/ArtifactList.test.tsx.snap
Labels: approved, lgtm, size/XXL

#110 Support update artifact/execution type in metadata
  WORKSPACE
  api/service.pb.go
  api/service.pb.gw.go
  api/service.proto
  api/service.swagger.json
  service/service.go
  service/service_test.go
  test/e2e/artifact_model_1.json
  test/e2e/make_requests.sh
  test/e2e/update_execution_type.json
  test/e2e/update_model_type.json
Labels: approved, lgtm, ok-to-test, size/XL
