Repository kubeflow/metadata, pull requests merged in 2019-06, with the labels that each got.

#42 Add MySql password flag
  Makefile
  server/main.go
Labels: approved, lgtm, size/S

#43 Add example requests to the backend API
  api/service.pb.go
  api/service.pb.gw.go
  api/service.proto
  api/service.swagger.json
  service/service.go
  test/e2e/artifact_model_1.json
  test/e2e/make_requests.sh
Labels: approved, lgtm, size/XL

#44 Add handlers for Execution and ExecutionType.
  api/api.pb.go
  api/api.proto
  api/service.pb.go
  api/service.pb.gw.go
  api/service.proto
  api/service.swagger.json
  service/metadata_store.go
  service/service.go
  service/service_test.go
Labels: approved, lgtm, size/XXL

#46 Added issue/pr template.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/M

#47 Add endpoint to list artifact by type
  api/service.pb.go
  api/service.pb.gw.go
  api/service.proto
  api/service.swagger.json
  service/service.go
  service/service_test.go
  test/e2e/make_requests.sh
Labels: approved, lgtm, size/L

#45 Python SDK: implement `log` method to record artifacts
  Makefile
  api/generate_proto.sh
  api/service.swagger.json
  sdk/python/kfmd/metadata.py
  sdk/python/tests/run_tests.sh
  sdk/python/tests/test.py
Labels: approved, lgtm, size/L

#49 Update API to export MLMD types directly.
  api/BUILD.bazel
  api/service.pb.go
  api/service.pb.gw.go
  api/service.proto
  api/service.swagger.json
  schemaparser/BUILD.bazel
  schemaparser/register.go
  service/BUILD.bazel
  service/service.go
  service/service_test.go
Labels: approved, lgtm, size/XXL

#51 add bazel version info
  README.md
Labels: approved, lgtm, size/XS

#50 Update python SDK to adapt new artifact protobuf
  .gitignore
  Makefile
  api/service.pb.go
  api/service.pb.gw.go
  api/service.proto
  schemaparser/register.go
  schemaparser/schemaset.go
  sdk/python/kfmd/metadata.py
  sdk/python/tests/test.py
  test/e2e/artifact_model_1.json
Labels: approved, lgtm, size/L

#52 Add db options in the server
  Makefile
  server/main.go
  test/e2e/make_requests.sh
Labels: approved, lgtm, size/M

#53 Add list artifacts by type into Python SDK
  sdk/python/kfmd/metadata.py
  sdk/python/tests/test.py
Labels: approved, lgtm, size/L

#54 Demo notebook
  sdk/python/README.md
  sdk/python/demo.ipynb
Labels: approved, lgtm, size/L

#58 Update swagger generation script to avoid duplicated HTTP path
  api/generate_proto.sh
  api/service.swagger.json
  sdk/python/kfmd/metadata.py
  service/service.go
Labels: approved, lgtm, size/M

#64 ListArtifacts should return an empty list if no artifacts exists
  service/service.go
  service/service_test.go
Labels: approved, lgtm, size/M

#68 Uses correct env variable in frontend server and removes host from API server
  frontend/server/server.ts
  server/main.go
Labels: approved, lgtm, size/XS

#66 Register predefined execution type
  schemaparser/register.go
  test/e2e/make_requests.sh
Labels: approved, lgtm, size/M

#65 Add endpoint for connecting artifacts to executions as input/output
  api/generate_proto.sh
  api/service.pb.go
  api/service.pb.gw.go
  api/service.proto
  api/service.swagger.json
  service/metadata_store.go
  service/service.go
  service/service_test.go
Labels: approved, lgtm, size/XL

#74 Add an license file into the docker image.
  Dockerfile
  api/service.proto
Labels: approved, lgtm, size/XS

#75 Generate pb.go and swagger.json
  api/service.pb.go
  api/service.pb.gw.go
  api/service.swagger.json
Labels: approved, lgtm, size/L
